apiVersion: v1
kind: PersistentVolume
metadata:
  name: dbpv01
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /public/01
    server: 192.168.137.20
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dbpv02
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /public/02
    server: 192.168.137.20
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dbpv03
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /public/03
    server: 192.168.137.20
